### ISSUE TITLE
ConflictingBeanDefinitionException: Annotation-specified bean name 'kafkaProducer' already existed

### ISSUE THREAD

**Issue by GenshenWang** [stavshamir/springwolf#25]
Hi, while I running project, there  occurs a exception : 
`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.caocao.dic.charge.DicChargeApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'kafkaProducer' for bean class [io.github.stavshamir.springwolf.producer.KafkaProducer] conflicts with existing, non-compatible bean definition of same name and class [com.caocao.dic.charge.server.mq.producer.KafkaProducer]
`
If project already exist class `KafkaProducer`, then will conflict with the class `io.github.stavshamir.springwolf.producer.KafkaProducer`. **How should I solve the problem?**

**Comment by stavshamir** [comment]
Thanks for reporting this problem! Obviously naming this bean with a common name such as `kafkaProducer` was a mistake on my part. I will fix it in the coming days. If you wish, you can provide a pull request yourself, changing the name of the bean from `kafkaProducer` to `springwolfKafkaProducer`.

In the meanwhile, if possible, to you can change the name of your bean from `kafkaProducer` to something else, but I understand this may be inconvenient.
